# Generated by Django 6.1 on 2026-08-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(blank=True, max_length=64)),
                ('customer', models.JSONField(default=dict)),
                ('items', models.JSONField(default=list)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Bangles', 'Bangles'), ('Anti-Tarnish Chains', 'Anti-Tarnish Chains'), ('Anti-Tarnish Bracelets', 'Anti-Tarnish Bracelets'), ('Hair Accessories', 'Hair Accessories'), ('Designer Jewelry', 'Designer Jewelry'), ('Temple Jewels', 'Temple Jewels'), ('Chokers', 'Chokers'), ('Ear Chain', 'Ear Chain')], max_length=64)),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('both', 'Sale & Rent')], default='sale', max_length=8)),
                ('price', models.PositiveIntegerField(default=0)),
                ('rent_price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=32)),
                ('image', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
