# Generated by Django 6.1 on 2026-08-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_razorpay_order_id_order_razorpay_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminOTP',
        ),
    ]
