# Generated by Django 6.1 on 2026-08-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_razorpay_order_id_order_razorpay_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bangles', 'Bangles'), ('Anti-Tarnish Chains', 'Anti-Tarnish Chains'), ('Anti-Tarnish Bracelets', 'Anti-Tarnish Bracelets'), ('Hair Accessories', 'Hair Accessories'), ('Designer Jewelry', 'Designer Jewelry'), ('Temple Jewels', 'Temple Jewels'), ('Chokers', 'Chokers'), ('Earings', 'Earings')], max_length=64),
        ),
    ]
